server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: retail-backoffice-api
  profiles:
    active: dev
#  cache:
#    type: simple
#    cache-names:
#      - customers
#

jpa:
  hibernate:
    ddl-auto: validate
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      format_sql: true
      use_sql_comments: true
      jdbc:
        batch_size: 20
      order_inserts: true
      order_updates: true
  show-sql: false

cache:
  type: ehcache
  ehcache:
    config: classpath:ehcache.xml

jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache
  endpoint:
    health:
      show-details: when_authorized

datasource:
  url: jdbc:sqlserver://localhost:1433;databaseName=SaleDockCelerant;trustServerCertificate=true
  username: dev1
  password: dev1
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 300000
    max-lifetime: 1200000
    connection-timeout: 30000
logging:
  level:
    com.saledock.api: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

